; This is an .INI file, used as a simple way to tune a game without recompiling/hardcoding it.
; A great place for gameplay variables and more. Another example of data-driven programming. 
[Level1]
levelFile=../Levels/GameLevel.json
modelPath=../Models
waveFile=../Levels/LevelData/Level1.json
[Level2]
levelFile=../Levels/GameLevel.json
modelPath=../Models
waveFile=../Levels/LevelData/Level2.json
[Level3]
levelFile=../Levels/GameLevel.json
modelPath=../Models
waveFile=../Levels/LevelData/Level3.json
[Player]
model=Fighter
hitpoints=1
speed=25.0
firerate=0.20
invulnPeriod=3
lives=3
respawnDelay=1.0
[Shaders]
pixel=../Shaders/LevelPixel.hlsl
vertex=../Shaders/LevelVertex.hlsl
starPixel=../Shaders/StarPixel.hlsl
starVertex=../Shaders/StarVertex.hlsl
[Window]
height=768
width=1024
xstart=100
ystart=100
[Enemy1]
model=UFO
hitpoints=4
speed=8.0
score=200
firerate=1.0
scale=1
[Bullet]
model=Bullet
speed=60.0
[EnemyBullet]
model=YellowBullet
speed=45.0
[Sounds]
gpmusic =../Dev5Sounds/Music/TheFifthQuadrant.wav
psmusic =../Dev5Sounds/Music/pausedBG.wav
phit =../Dev5Sounds/HitSound/WAB.wav
pshoot =../Dev5Sounds/ShootSound/attack.wav
pdeath =../Dev5Sounds/DeathSound/explode.wav
menu =../Dev5Sounds/Pause/Digital C.wav
ehit =../Dev5Sounds/HitSound/DDH.wav
edeath =../Dev5Sounds/DeathSound/Popup.wav
[Global]
scrollSpeed = 0.75
[DropRate]
Carrier = 100
SideFighter = 25
MultiShot = 25
ScreenWipe = 12
ExtraLife = 8
BonusPoints = 30
[Explosion]
model = ExplosionQuad
totalFrames = 16
frameTime = 0.05
lifeTime = 0.8
[PowerUps]
duration = 10.0
SideFighterIcon_Path = ../Models/Textures/PowerUp_Icons/SideFighter_Icon.png
MultiShotIcon_Path = ../Models/Textures/PowerUp_Icons/MultiShot_Icon.png
; If you change this file it will replace the saved.ini version if its newer. 
